### ISSUE TITLE
Bounding box issue

### ISSUE THREAD

**Issue by cstancu** [cytoscape/cytoscape.js-dagre#10]
Trying to draw the following graph:
```
{
  "elements" : {
  "nodes": [
      { "data": { "id": "top", "label": "top"} },
      { "data": { "id": "foo", "label": "foo", "parent": "top"} },
      { "data": { "id": "bar", "label": "bar", "parent": "top"} },
      { "data": { "id": "baz", "label": "baz", "parent": "top"} }
    ],
    "edges": [
    ]
  }
}
```

,with the following layout:
```
var dagreLayout = {
  name: 'dagre',
  rankDir: 'TB',
  fit: true,
  boundingBox: {
    x1: 0, y1: 0, x2: 560, y2: 376, w: 560, h: 376
  }
};
```
results in only the top compound node being draw, with no child elements:
![top](https://cloud.githubusercontent.com/assets/1731630/14164814/d7f8404a-f6b7-11e5-8549-e39e8405e915.jpg)

(Note: The effect of having the label of the compound element inside the node was achieved by simply setting `padding-top: "50px"` for compound nodes, so that cannot be the cause of this issue.) 

If I remove the boundingBox restriction from the layout the result is correct:
![correct](https://cloud.githubusercontent.com/assets/1731630/14164850/26a45c24-f6b8-11e5-877b-3105aaea53c4.jpg)

Also, if I add an edge between two child nodes, without removing the boundingBox restriction, the result is correct: 
![correct2](https://cloud.githubusercontent.com/assets/1731630/14164906/a709361e-f6b8-11e5-99e2-24fbd1095a42.jpg)

The problem seems to be caused by how the dagreBB bounding box object is computed in cytoscape-dagre.js. If I print the dagreBB object when the display problem occurs I get:
`dagreBB: {"x1":56.25,"x2":244.25,"y1":43.25,"y2":43.25,"w":188,"h":0}`. It looks like since the three child nodes have the same `y` coordinate the `dagreBB.h` field ends up being 0.

A simple workaround is to test if `dagreBB.h` is 0, then give it a positive value and also update `dagreBB.y2`:
```
        if(dagreBB.h === 0) {
          var h = nodes.first().height();
          dagreBB.h = h;
          dagreBB.y2 = dagreBB.y1 + h;
        }
```
 , in this case I use the height of the first node in the collection. The result is:
![correct3](https://cloud.githubusercontent.com/assets/1731630/14165166/c1489db0-f6ba-11e5-8801-4059b0fea0cb.jpg)

As a side node, it looks like the boundingBox layout  functionality forces the graph to occupy the entire area of the specified box. When I learned about this feature I thought it was a maximal bounding box, i.e., the graph takes as much space as it needs between the specified bounds. Maybe such a feature would be useful too.

**Comment by maxkfranz** [comment]
@cstancu This doesn't seem to be an issue using the latest version of Cytoscape and the extension.

I suspect the issue is only to do with your use of the padding -- which relies on a bug -- for label placement.
