### ISSUE TITLE
Dagre layout "DEPRECATED"

### ISSUE THREAD

**Issue by Patileo** [cytoscape/cytoscape.js-dagre#111]
In the README you write that the layout is organised using dagre. If I understand it correctly, you use "Dagre" for this. On the GitHub page of Dagre it says that the project is "DEPRECATED" and that it has no maintainer. Now my questions: Can this have a negative effect on "Cytoscape.js-dagre" in the future? Are there already known problems/errors because of this? Can I currently use it without hesitation?

**Comment by maxkfranz** [comment]
> In the README you write that the layout is organised using dagre. If I understand it correctly, you use "Dagre" for this. 

Yes

> On the GitHub page of Dagre it says that the project is "DEPRECATED" and that it has no maintainer. 

[Chris](https://github.com/cpettitt) created the Dagre library.  He did an excellent job, and the library is mature.  It's understandable that he's moved on.

It would be unreasonable to assume that he would support it for everyone, indefinitely, without commensurate compensation.  I'm sure you wouldn't expect that, but it bears mentioning for others who come across this issue in future.

> Now my questions: Can this have a negative effect on "Cytoscape.js-dagre" in the future? 

For your purposes, that depends on your project's requirements in conjunction with the current abilities of Dagre.

One might take the view that Dagre is simply an algorithm, like quick sort.  Once a good implementation of quick sort has been made, what reasons might there be to change it?  Further, what risks might be raised by frequently changing a quick sort implementation that already functions well?

In the event that you really need to change Dagre, you could benefit from the fact that it's open source, with a permissive license.  Additionally, this wrapper extension for Cytoscape is open to pull requests from the community.

> Are there already known problems/errors because of this? 

Best to browse Dagre's issue tracker, try the library yourself, and make an assessment re. your project.

> Can I currently use it without hesitation?

Ultimately, that's for you to decide.
