### ISSUE TITLE
Missing options for rankDir in typings

### ISSUE THREAD

**Issue by bunsenbeaker** [cytoscape/cytoscape.js-dagre#118]
Hi, I'm using cytoscape-dagre in a typescript/Angular app and it seems like option BT is missing from rankDir in DagreLayoutOptions. While option is indeed supported, it is not in the typings therefore build errors occure.

**Comment by maxkfranz** [comment]
Right now, the place to submit amendments to the community-supportewd type definitions is on DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped

We’re planning on supporting first-party definitions in future, and we’re using this issue to coordinate with contributors: https://github.com/cytoscape/cytoscape.js/issues/3166
