### ISSUE TITLE
Left aligning node edges

### ISSUE THREAD

**Issue by tylerecouture** [cytoscape/cytoscape.js-dagre#13]
Is there a way to Left or Right align node edges? By default they are center aligned (up and down).  Thanks!

EDIT: I should add, I am using 'text-valign': 'center', so the nodes contain the labels:                       'width': 'label',
'height': 'label',

**Comment by maxkfranz** [comment]
From the docs: 

```js
rankDir: undefined, // 'TB' for top to bottom flow, 'LR' for left to right
```
