### ISSUE TITLE
nodes and edges overlap, how to overcome this?

### ISSUE THREAD

**Issue by Mafti** [cytoscape/cytoscape.js-dagre#15]
Hi,

I am curious what I have to do to prevent edges to overlap the nodes.
see https://jsfiddle.net/hnjwrL9z/2/

**Comment by maxkfranz** [comment]
(1) Dagre.js has no concept of compounds.

(2) Increase separation using the options.  Or look into implementing #5 if bent edges suit your usecase.  We always appreciate pull requests!
