### ISSUE TITLE
large set doesn't produce a TB look

### ISSUE THREAD

**Issue by Mafti** [cytoscape/cytoscape.js-dagre#16]
Hi,

attached is my test-file of using dagre and cytoscape.
for some reason, this graph is look rather strange.
I expect more visible hierachy, but instead it's just 1 row graph.
even though I have set it to TB.

what am I doing wrong?
(please not that level is my custom attribute, is it by any chance a reserved word? )

[testdagre.zip](https://github.com/cytoscape/cytoscape.js-dagre/files/517966/testdagre.zip)

**Comment by maxkfranz** [comment]
You're using compound nodes.  The Dagre library has no concept of compounds.  Refer to the Dagre docs: https://github.com/cpettitt/dagre/wiki
