### ISSUE TITLE
I set the weight of nodes, but it does't alter the appearance.

### ISSUE THREAD

**Issue by SOSDAN** [cytoscape/cytoscape.js-dagre#18]
environment: chrome browser
code:
`<script type="text/javascript">
			var cy = cytoscape({
				container: document.getElementById("cy"),
				autolock: true,
				userPanningEnabled: true
			});
			cy.add([{
				group: "nodes",
				data: {weight: 10, id: "13177345979"},
				position: {x: 200, y: 200}
			}, {group: "nodes", data: {weight: 10, id: "15801094535"}, position: {x: 100, y: 250}}
			, {group:  "edges", data: {id: "e0", source: "13177345979", target: "15801094535"}}]);
		</script>`
I have set the weight of two nodes in the code, but it turnes out that, both nodes share the same weight.

**Comment by maxkfranz** [comment]
Edges are weighted, not nodes.  And you have to set the options for the layout as stated in the readme (using `edgeWeight`).

**Comment by SOSDAN** [comment]
thank you.  how can I set the size of a node?
