### ISSUE TITLE
When nodes use parent option - not performing layout?

### ISSUE THREAD

**Issue by butchmarshall** [cytoscape/cytoscape.js-dagre#19]
Is there a way to make this layout type work with the data "parent" option?

with "parent"
![image](https://cloud.githubusercontent.com/assets/339763/20867776/22623660-ba1a-11e6-8bb7-760d6ed04c1a.png)

without "parent"
![image](https://cloud.githubusercontent.com/assets/339763/20867791/4b2d0386-ba1a-11e6-915a-5c44010c6803.png)

cytoscape-cose-bilkent seems to handle it, but it's no dagre
![image](https://cloud.githubusercontent.com/assets/339763/20867850/7646a134-ba1b-11e6-9f7e-82ee15b1e497.png)

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js-dagre/issues/14

**Comment by butchmarshall** [comment]
Thanks!

**Comment by maxkfranz** [comment]
@butchmarshall Maybe could this be patched generally in the extension?  It's not really reasonable to create dummy elements on the Cy.js side in the extension, but Dagre has its own model for elements.

If I'm understanding your workaround correctly, it's just replacing compound-compound and compound-leaf edges with every combination of leaf-leaf edges so Dagre has something to go on.

Maybe the extension could detect compound graphs and patch the model sent to Dagre with your workaround.  I'm not sure if it would work with large compound hierarchies, but it would probably work well enough for depths of 1 or 2.

Would you be interested in porting your workaround into the extension in a pull request?  Thanks
