### ISSUE TITLE
Edge overlap

### ISSUE THREAD

**Issue by ssmereka** [cytoscape/cytoscape.js-dagre#21]
Not sure if this issue is related to cytoscape, cytoscape.js-dagre, or the underlying dagre library.  My guess is with dagre, but just incase:

In the following example an edge is being hidden behind another edge.   See the code in this [JSFiddle](https://jsfiddle.net/6ss0a9on/1/).

<img width="250" alt="degree-hidden-edge" src="https://cloud.githubusercontent.com/assets/489291/23554587/c3d455fe-fff3-11e6-93b1-7ce8f0d3b7f1.png">

If we move nodes `C`, `D`, `E`, and `F` you can see the hidden edge.

<img width="250" alt="dagre-hidden-edge-2" src="https://cloud.githubusercontent.com/assets/489291/23554589/c5ab0332-fff3-11e6-8bb2-908b6a292ee0.png">

Cross posted this issue in dagre as well:  [Issue #211](https://github.com/cpettitt/dagre/issues/211)

**Comment by maxkfranz** [comment]
See https://github.com/cytoscape/cytoscape.js-dagre/issues/5
