### ISSUE TITLE
No render edges when use the newer Cytoscape-v3.1.0

### ISSUE THREAD

**Issue by fraespre** [cytoscape/cytoscape.js-dagre#23]
Hi,
Now I have a graph app works fine ( cytoscape-2.7.17 ,  dagre-0.7.4 and cytoscape-dagre-1.5.0 )
Recently I have tried to upgrade Cytoscape to newer version 3.0.0 or 3.1.0. But using this latest versions the graph is wrong. Any error is displayed by the console , however the edges are hidden and all nodes are drawn in the same position.

Could you review it. I think that can be necesary to update "cytoscape-dagree".

Regards,

**Comment by maxkfranz** [comment]
The layout is working fine on both the main site and the demo in this repo: http://js.cytoscape.org/demos/dagre-layout/

You can't update a lib with a major version number bump without fixing your code for that version: http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/

**Comment by fraespre** [comment]
yeaaah
I have reviewed my code using the references you said, and I have detected where is my problem. Now I have fixed it and it works fine.

Thank you very much,

**Comment by maxkfranz** [comment]
Good to hear it's working for you.  Let me know if you run into any other issues with 3.x
