### ISSUE TITLE
nodes are undefined

### ISSUE THREAD

**Issue by swarajd** [cytoscape/cytoscape.js-dagre#25]
I am getting this issue when creating a production ready application (minified/uglified/etc): 
![image](https://user-images.githubusercontent.com/1250084/27391527-2da292c8-5672-11e7-9296-ac1eedb63ee5.png)
. I found the source of the issue to be this: 
![image](https://user-images.githubusercontent.com/1250084/27391545-3531510a-5672-11e7-865a-0c2c5f8eacff.png)
. Some elements are undefined when being iterated over. I found the issue here: 
![image](https://user-images.githubusercontent.com/1250084/27391555-3c5027cc-5672-11e7-8a5f-0fbeb898a0e7.png)
, and fixed it by doing this: 
![image](https://user-images.githubusercontent.com/1250084/27391565-41303480-5672-11e7-9560-43c2f8152e8a.png) I added the if statements to check for nullness/undefinedness. 

I thought this would be the only fix I needed to do but there were MANY more after that. The thing is, this never happened with the dev server running, it only happened when I built for production. If it means anything I am using preact-cli and am to the mercy of whatever minifier/uglifier they are using. Would it be better to manually add the null checks in the dagre code and submit a pull request or take another course of action?

**Comment by developit** [comment]
@swarajd There's a lot of tech here to sift through, but your screenshots got me wondering:  where are you kicking off Cytoscape in your code?  Curious if it's in componentWillMount or componentDidMount.

**Comment by maxkfranz** [comment]
This extension is just a wrapper for the Dagre lib.  If there's a problem in the Dagre lib, it would have to be handled there.

**Comment by sakopqiu** [comment]
> I am getting this issue when creating a production ready application (minified/uglified/etc):
> ![image](https://user-images.githubusercontent.com/1250084/27391527-2da292c8-5672-11e7-9296-ac1eedb63ee5.png)
> . I found the source of the issue to be this:
> ![image](https://user-images.githubusercontent.com/1250084/27391545-3531510a-5672-11e7-865a-0c2c5f8eacff.png)
> . Some elements are undefined when being iterated over. I found the issue here:
> ![image](https://user-images.githubusercontent.com/1250084/27391555-3c5027cc-5672-11e7-8a5f-0fbeb898a0e7.png)
> , and fixed it by doing this:
> ![image](https://user-images.githubusercontent.com/1250084/27391565-41303480-5672-11e7-9560-43c2f8152e8a.png) I added the if statements to check for nullness/undefinedness.
> 
> I thought this would be the only fix I needed to do but there were MANY more after that. The thing is, this never happened with the dev server running, it only happened when I built for production. If it means anything I am using preact-cli and am to the mercy of whatever minifier/uglifier they are using. Would it be better to manually add the null checks in the dagre code and submit a pull request or take another course of action?

Is there any method to work around this error? I am also deeply confused by this problem. And this problem still exists even if I use development build...
