### ISSUE TITLE
No `ranker` option in this extension?

### ISSUE THREAD

**Issue by josephrocca** [cytoscape/cytoscape.js-dagre#26]
The dagre library [seems to have](https://github.com/cpettitt/dagre/wiki#configuring-the-layout) a `ranker` option which takes values `longest-path`, `network-simplex` and `tight-tree`. Is there any way to use those different algorithms in this extension? Thanks!

**Comment by maxkfranz** [comment]
If you'd like to add support for sending that option in the extension via a pull request, I'd be happy to review/merge it.

**Comment by skortchmark9** [comment]
@maxkfranz you can close this one now!

**Comment by maxkfranz** [comment]
The PR is in 2.1.0
