### ISSUE TITLE
Use Weaver.js

### ISSUE THREAD

**Issue by Prophet32j** [cytoscape/cytoscape.js-dagre#27]
Is it possible to use Weaver with the dagre layout? I don't see it as an option in the code, and I would like to be able to offload the work into a thread to not block the main thread.

**Comment by maxkfranz** [comment]
Not possible. Can't control dagre internals

**Comment by Prophet32j** [comment]
Is there any way to not block the main thread then? Allow for some sort of progress bar?

**Comment by maxkfranz** [comment]
Not without real threads
