### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by ypconstante** [cytoscape/cytoscape.js-dagre#29]
The demo link in the readme goes to a not existing page.

**Comment by maxkfranz** [comment]
You're looking at wip files in the repo.  Look at a tag or use the readme on npm.

The extensions are being updated with new scaffolding, but I haven't had any time to continue work on it for now: https://github.com/cytoscape/cytoscape.js/issues/1926

You can use the demo link for an extension once a new version has been published with the updates.
