### ISSUE TITLE
weird placement of leaves

### ISSUE THREAD

**Issue by benjaminaaron** [cytoscape/cytoscape.js-dagre#3]
Do you have an idea why this leaf is placed so far off one would expect it to?

![screen_shot_2015-11-20_at_02_49_09](https://cloud.githubusercontent.com/assets/5141792/11289904/9b0bd112-8f31-11e5-9376-3ec8613845c8.png)

The settings are:
````
layout: {
    name: 'dagre', 
    rankDir: 'LR'
}
```
The same effect happens with `rankdir: 'TB'` to a few leaves.

**Comment by maxkfranz** [comment]
The Dagre library itself is responsible for setting positions...

Any feedback for the Dagre algorithm should go to its develoeprs: https://github.com/cpettitt/dagre
