### ISSUE TITLE
Updating dagre dependency

### ISSUE THREAD

**Issue by janniclas** [cytoscape/cytoscape.js-dagre#30]
Hey Guys,

I have just noticed that the dependency for the dagre library is set on 0.7.4 which has been released over 2 years ago.
 It seems like the project was recently picked up again and it got a few updates over the last couple of months, especially updating their dependencies to newer versions.
Wouldn't it be a good idea to update the dependency to this new version? 

Best regards,
Jan-Niclas

**Comment by maxkfranz** [comment]
I'll see if it can be rolled into the scaffolding update (https://github.com/cytoscape/cytoscape.js/issues/1926)

Do you know if they made any breaking changes or only minor patches?

**Comment by janniclas** [comment]
I am not sure, I can look into it tomorrow. 
Today I just updates the dependency in a local copy of mine and everything seemed to work Fine.

**Comment by maxkfranz** [comment]
0.8.1 should be semver compatible with ^0.7.4, so it should already be upgrading automatically if you `npm update`

**Comment by janniclas** [comment]
You are right, but if you take a look at the published version of cytoscape-dagre ( https://yarnpkg.com/en/package/cytoscape-dagre ), you will see that the 2.1.0 version contains the dependency ~0.7.4 not ^0.7.4.
I known I can work around this by getting the master branch instead of the version published at npm but I think it would be good to update the published version anyways.

**Comment by maxkfranz** [comment]
See release cytoscape-dagre@2.2.0
