### ISSUE TITLE
dagre need to be update

### ISSUE THREAD

**Issue by YikaJ** [cytoscape/cytoscape.js-dagre#34]
There is a mistake which cause by dagre's dependency graphlib@^1.0.5,.

here is the wrong code

in graphlib@^1.0.5

```js
Graph.prototype.sources = function() {
  return _.filter(this.nodes(), function(v) {
    return _.isEmpty(this._in[v]);  // Uncaught TypeError: Cannot read property '_in' of undefined                
  }, this);
};
```

And In graphlib@^2.1.5, it had already fix it.

```js
Graph.prototype.sources = function() {
  var self = this;
  return _.filter(this.nodes(), function(v) {
    return _.isEmpty(self._in[v]);  // use self to fix the 'this' problem
  });
};
```

It's dagre's mistake, but I think this lib should update it to avoid the error causes.I have try to update dagre@^v0.8.2 by myself, and it works well by now, maybe your team can do more test on it.

Thanks a lot for your team to provide such a great project.

**Comment by maxkfranz** [comment]
Merged and released as v2.2.2 patch
