### ISSUE TITLE
The layout becomes too sparse when there are multiple groups (cosmetic issue)

### ISSUE THREAD

**Issue by swarajd** [cytoscape/cytoscape.js-dagre#36]
When there are multiple groups/nodes, the edges become too long. I'm not sure if this is expected behavior or something that can be tweaked in settings. 

<img width="978" alt="screen shot 2018-09-18 at 11 46 01 am" src="https://user-images.githubusercontent.com/1250084/45700040-8f822080-bb39-11e8-97fc-26fd75783faf.png">

**Comment by maxkfranz** [comment]
This is just a wrapper of Dagre as a Cytoscape layout.  If you have any algorithmic feedback, it should be to that repo: https://github.com/dagrejs/dagre

**Comment by swarajd** [comment]
Fixed by enabling animation and setting the duration to 0. The problem isn't fixed, but for my purposes it is. Closing.
