### ISSUE TITLE
complete Graph disapperars on certain zoom level

### ISSUE THREAD

**Issue by FullyScaled** [cytoscape/cytoscape.js-dagre#38]
Hello,
im using the cytoscape dagre layout. Unfortunately there occurs a problem on certain zoom levels: The complete graphical graph output disappears on those zooming levels. If I change the zoom (more or less) the graph is showing again. 

Is this a problem that you know about and if yes is there a fix for that? If not I´ll try to provide a demo for that.
best regards

**Comment by maxkfranz** [comment]
This is not a known issue.  Please provide a reproducible test case, including:

- Browser version
- OS version
- A code sample that reproduces the issue.  Any of the example demos on [js.cytoscape.org](http://js.cytoscape.org) can be forked on JSBin to easily provide a code sample.

**Comment by maxkfranz** [comment]
If it doesn’t happen in the latest 3.2 or 3.3, then it should already be
resolved. Thanks
