### ISSUE TITLE
Preserve old nodes' positions on layout re run, when a new set of nodes are added to the graph?

### ISSUE THREAD

**Issue by utkarshagarwal01** [cytoscape/cytoscape.js-dagre#40]
I basically want to know if there is a functionality in dagre like `randomize: false` which is available in layouts like cose-bilkent where the old node positions are respected when the layout is re run after adding a new set of nodes(more specifically, after expanding a compound node using [expand-collapse](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse).

**Comment by virmundi** [comment]
I've just been playing with this for a few minutes, but I found sorting the nodes to help. In my case each node has an id. The graph appears, on a small graph of about 10 nodes, stable.

**Comment by maxkfranz** [comment]
This is up to how dagre itself works.  If you want new dagre features, you should post issues on the dagre issue tracker.

https://github.com/dagrejs/dagre/issues
