### ISSUE TITLE
Controlling nodes positions

### ISSUE THREAD

**Issue by pmario26** [cytoscape/cytoscape.js-dagre#41]
I'm currently working on a project that has been using the Cytoscape Dagre implementation for a long time. The lib is fantastic and always met the project needs until now but there is one new feature that i'm currently unable to implement.
I would like to know if in the current version of the lib is there any way i can control the position of nodes to keep them aligned.
For example:
![image](https://user-images.githubusercontent.com/18668861/53021501-1d8b6b80-3438-11e9-846e-3f944659bfa3.png)
I would like to keep some of the nodes in the graph above aligned like in the picture below:
![image](https://user-images.githubusercontent.com/18668861/53021879-ee292e80-3438-11e9-938a-40ea2e4b4591.png)
I think this would improve greatly the understanding of some graphs, even if it increased the number of crossing edges as a side effect.
Is there anyway i can achieve that with the current version of the lib ?
If not, how could i contribute changing the lib to achieve that ?

**Comment by maxkfranz** [comment]
The dagre lib itself would have to be changed.  This is just a wrapper.

See https://github.com/dagrejs/dagre
