### ISSUE TITLE
Upgrade webpack to 4.32.2

### ISSUE THREAD

**Issue by n313893254** [cytoscape/cytoscape.js-dagre#43]
I import cytoscape-dagre in ember.js and cannot work after the build. The error is `Not possible to find intersection inside of the rectangle`. 

After upgrade webpack to 4.32.2 version. cytoscape-dagre works well. 

So I suggest to  Upgrade webpack to 4.32.2.

**Comment by maxkfranz** [comment]
That looks like an issue with Dagre and/or your data, not the build process.

Please demonstrate that there is a precise issue with the build process and that upgrading webpack would solve it.
