### ISSUE TITLE
Dagre control points for drawing more accurate edges

### ISSUE THREAD

**Issue by danielpes** [cytoscape/cytoscape.js-dagre#5]
It would be nice if thie cytoscape-dagre layout could make the edges "[points](https://github.com/cpettitt/dagre/wiki#output-graph)" attribute available for the cytoscape graphs, giving the possibility to draw more accurate edges with segments or unbundled-bezier styles.

**Comment by djangosdk** [comment]
I was having same thought ...
From example http://cpettitt.github.io/project/dagre-d3/latest/demo/tcp-state-diagram.html ,
Is it possible to have edges like above example in cytoscape ?
Edges that go straight and bend as per location ..

**Comment by djangosdk** [comment]
see cytoscape.js vs dagre-d3.js for same set of data.

- cytoscape : https://jsfiddle.net/bababalcksheep/m40m5mmx/6/
- dagre-d3: http://cpettitt.github.io/project/dagre-d3/latest/demo/tcp-state-diagram.html 

How can I behave cytoscape edges same like dagre ?
Any help will be much appreciated

**Comment by maxkfranz** [comment]
Not easy to do until 2.7 is released with style properties for configuring where the `segment-weights` start and end: https://github.com/cytoscape/cytoscape.js/issues/1236

**Comment by djangosdk** [comment]
@maxkfranz 2.7 is released. Waiting for this feature. Thankx

**Comment by maxkfranz** [comment]
@djangosdk There are a lot of other tasks for Cytoscape.js that have to take priority.  If this feature is important to you, we'll gladly accept a pull request.  It should be straightforward to implement in 2.7.  The [segments property values](http://js.cytoscape.org/#style/segments-edges) should go in user specified `node.data()` fields so the user can map to them in their stylesheet.

**Comment by djangosdk** [comment]
@maxkfranz 
Can you still help with some basic example or point me in right direction. I am in dire need for Dagre control points for Cy.
A description of what to do , where to do will also help ( I did not understand fully how to utilize  segments property values )

**Comment by newlukai** [comment]
I spent some time trying to convert Dagre's control points to Cytoscape's segment edges (distances and weights). Unfortunately, the rendered result is not that beautiful, but maybe it's a start to get this issue done?

[https://github.com/newlukai/cytoscape.js-dagre/commit/3a0a7c41e37cc4e2fd00ba7068746c1627a37935](A first version of implementing this issue).

**Comment by knownact** [comment]
@newlukai I have improved your implementation, make it more beautiful. please check it out.

3bef946c348d419366c8b75b0bd3a2ee3ac28e34

**Comment by knownact** [comment]
and fix when rankDir is "LR":

af46725944e8d294179fe6f5d344679f7d025694

**Comment by yansenlei** [comment]
@knownact 
Is it like this?http://jsfiddle.net/5u9mzfse/47/

**Comment by knownact** [comment]
Now, the result is like this:
![image](https://user-images.githubusercontent.com/15138165/37500860-ab1328e6-2906-11e8-8418-1b65d81c482e.png)

**Comment by knownact** [comment]
By the way , I think default result is good.

https://jsfiddle.net/knownact/usL3ayxn/3/

**Comment by yansenlei** [comment]
@knownact 
If it is drawing a flow chart, Klay shows better.
dagre:
![image](https://user-images.githubusercontent.com/23315895/37502287-0a1780c0-290d-11e8-9203-b8946055b3f7.png)

klay:
![image](https://user-images.githubusercontent.com/23315895/37502225-be562aec-290c-11e8-84db-10068ed0058e.png)

**Comment by knownact** [comment]
@yansenlei yep, but can you give me the test data? i think dagre is not bad like this:

![image](https://user-images.githubusercontent.com/15138165/37504487-9541967a-2919-11e8-861d-de5b4aab85d6.png)

**Comment by yansenlei** [comment]
sure, like this: https://jsfiddle.net/leiys/e2rc66b8/3/

**Comment by knownact** [comment]
this is what a get:

![image](https://user-images.githubusercontent.com/15138165/37506411-abb684dc-2924-11e8-9924-31babe101e02.png)

**Comment by yansenlei** [comment]
yes, this layout is not like a flowchart.

**Comment by knownact** [comment]
yep, Klay is better!

**Comment by newlukai** [comment]
Since I was in the need to find a solution, I switched to mxGraph. It's not as light-weight as cytoscape, but the provided layouts do fine and I'm now able to make very specific changes to the graph.

@knownact : Your changes look good.

Regarding the discussion started shortly: Yes, Klay is better.

**Comment by mafar** [comment]
can we get this feature ?

**Comment by maxkfranz** [comment]
Dagre can only inform where the edges should be routed for the node positions that Dagre specifies.  As soon as the nodes are moved, Dagre's assumptions are no longer true and the use of Dagre's edge points would give bad results.

For trees -- and probably some types of DAGs as well -- specifying the points from Dagre itself isn't really needed in `cytoscape>=3.5`.   The `curve-style:taxi` edge style allows for automatic routing of an edge using taxicab geometry.  This gives a very similar result as Dagre's edge points, except the native Cytoscape taxi feature works interactively whereas Dagre does not.

See https://github.com/cytoscape/cytoscape.js/issues/2306.  The example graph in that issue uses a Dagre layout with taxi edges.

**Comment by maxkfranz** [comment]
The example graph: ![screen shot 2019-02-19 at 5 12 38 pm](https://user-images.githubusercontent.com/989043/53051347-a8d12500-3469-11e9-8f8f-b4946a007a50.png)

**Comment by deepanshu11madan** [comment]
was anyone able to make the this work? I am facing the similar issue, why doesn't cytoscape.js-dagre follow the dagre layout for edges?

**Comment by deepanshu11madan** [comment]
Is there any future plan to make edges follow dagre layout?

**Comment by koo5** [comment]
hello stale bot, did microsoft send you to break opensource? It's not hard to see how changing the meaning of "closed" is perfectly counterproductive, is it?

**Comment by SatishChandraPalakoti** [comment]
I do not understand what the solution to overlapping paths is. Has this been addressed in any of the cytoscape versions ?

**Comment by rish1** [comment]
> this is what I get:
> 
> ![image](https://user-images.githubusercontent.com/15138165/37506411-abb684dc-2924-11e8-9924-31babe101e02.png)

How did u manage to draw an edge saperately in my case difference edges shares one i mean it merges down at some point

**Comment by danyel-motif** [comment]
Hey, @knownact -- I just wanted to thank you for the hard work you did on https://github.com/cytoscape/cytoscape.js-dagre/issues/5#issuecomment-373244016

It's lovely for my purposes. (And @maxkfranz , thanks for the library!)
