### ISSUE TITLE
Arrange itens side by side

### ISSUE THREAD

**Issue by calebeaires** [cytoscape/cytoscape.js-dagre#54]
**Feature Request**

Instead of arrange stand alone itens one above another, do it side by side (left-right).

Current behavior
![Captura de Tela 2020-01-14 às 22 03 44](https://user-images.githubusercontent.com/794195/72395992-07eef680-371a-11ea-9930-17eb7b384094.png)

Desired

![Captura de Tela 2020-01-14 às 22 03 57](https://user-images.githubusercontent.com/794195/72396015-16d5a900-371a-11ea-9d34-65bf018e60f6.png)

**Comment by maxkfranz** [comment]
This package is just a wrapper to the Dagre library to make the Dagre
algorithm work with Cytoscape.

If you have a feature request for the algorithm, you should make it in the
Dagre repo linked in the readme: https://github.com/dagrejs/dagre

**Comment by boramalper** [comment]
Hi @maxkfranz,

[Dagre clearly supports that](https://github.com/dagrejs/dagre/wiki#configuring-the-layout) so the question is I believe perfectly well-addressed in finding how to pass parameters to Dagre using your wrapper.

For instance, [cytoscape.js-klay](https://github.com/cytoscape/cytoscape.js-klay) options object has a dedicated `klay` field to pass parameters to the underlying library. Would you be interested in implementing (or reviewing & merging) such a fetaure?
