### ISSUE TITLE
Generate unminified distribution file during build file

### ISSUE THREAD

**Issue by mben-romdhane** [cytoscape/cytoscape.js-dagre#60]
In the switch between version 2.2.2 and version 2.3.0, the distributed file became minified. It would be great if the release process generated both minified and unminified files, as unminified files are useful for debugging, and it is not possible to run the npm pipeline for release on some systems due to restrictions.

**Comment by maxkfranz** [comment]
Amended in 2.3.1.  See 5be1653

**Comment by maxkfranz** [comment]
See also #58

**Comment by TyOverby** [comment]
Thanks @maxkfranz!
