### ISSUE TITLE
Add missing options in dagre layout

### ISSUE THREAD

**Issue by ethan-keller** [cytoscape/cytoscape.js-dagre#83]
Dear,

It would be great if you could add the missing dagre options such as e.g., 'align'. They are quite useful and I believe it would make `cytoscape.js-dagre` more "complete". 

I guess you would just need to explicitely specify the options in the `layout.js` file.

These are the options that are given on `dagre`'s (deprecated) repo [wiki](https://github.com/dagrejs/dagre/wiki):

Object | Attribute | Default | Description
-- | -- | -- | --
graph | rankdir | TB | Direction for rank nodes. Can be TB, BT, LR, or RL, where T = top, B = bottom, L = left, and R = right.
graph | align | undefined | Alignment for rank nodes. Can be UL, UR, DL, or DR, where U = up, D = down, L = left, and R = right.
graph | nodesep | 50 | Number of pixels that separate nodes horizontally in the layout.
graph | edgesep | 10 | Number of pixels that separate edges horizontally in the layout.
graph | ranksep | 50 | Number of pixels between each rank in the layout.
graph | marginx | 0 | Number of pixels to use as a margin around the left and right of the graph.
graph | marginy | 0 | Number of pixels to use as a margin around the top and bottom of the graph.
graph | acyclicer | undefined | If set to greedy, uses a greedy heuristic for finding a feedback arc set for a graph. A feedback arc set is a set of edges that can be removed to make a graph acyclic.
graph | ranker | network-simplex | Type of algorithm to assigns a rank to each node in the input graph. Possible values: network-simplex, tight-tree or longest-path

Thank you and happy holidays!
Ethan

**Comment by maxkfranz** [comment]
Which options in particular are you interested in?  It looks like these are (mostly?) already supported.

**Comment by maxkfranz** [comment]
Great, so we've narrowed it down to `align` and `acyclicer`.  Since you have graphs where you'd like to use these options, you're in a great position to test out the addition of those options.

I think you're right that it should just be a matter of passing the options along, so you're welcome to put up a quick PR for your proposed additions
